- CHANGELOG.MD
- assets/scripts/hyphenation.js
- assets/styles/base/_typography.scss
- lib/Constants.php
- partials/layouts/layout-hero.dust
- Loads shared assets now without domain information skipping CORS problems. 
- Adds `.no-hyphen` css class to disable hyphenation where applicable
- Adds `.no-hyphen` to hero `h1`
- Some assets failed to load on other domains
- Header hyphenation looked "weird" (that's a technical term)
> Fixes cross-origin asset loading, adds .no-hyphens

- lib/BlocksController.php
- lib/ThemeSupports.php
Upgrade hooks deprecated in WP 5.8.
Fixes deprecation notices in WP 5.8.
> Upgrade deprecated hooks

- lib/DustPressController.php
- lib/ThemeSupports.php
Remove `<img>` id attribute from output in order to prevent duplicate ids in site markup.
> a11y: Prevent duplicate img ids

- lib/Formatters/SitemapFormatter.php
- partials/ui/pagination.dust
Move invalid attribute `role` from list elements into a wrapping div.
> a11y: Move ul role attribute to a wrapping div

- CHANGELOG.MD
- lib/ACF/Fields/AccordionFields.php
- lib/Blocks/AccordionBlock.php
- lib/Formatters/AccordionFormatter.php
- lib/Traits/Components.php
Fixes bug by doing sanity checks to make sure it's array that's passed on.
> `Uncaught TypeError: Argument 1 passed to TMS\Theme\Base\Formatters\AccordionFormatter::handle_layouts() must be of the type array, bool given, called in tms-theme-base/lib/Formatters/AccordionFormatter.php on line 48 and defined in tms-theme-base/lib/Traits/Components.php:39`
> Fixes type error: expected array, got bool

- CHANGELOG.MD
- assets/styles/ui-components/_accessible-slick.scss
Before fix, there was no upper limit to image carousel item height making it pretty easy to break.
Most of the changes are sass-lint fixes.
Relevant change is the addition of `max-height: 320px;` after `min-height: 320px`.
TMS-142 and https://github.com/devgeniem/tms-theme-muumimuseo/pull/15
> TMS-142: Fix to image carousel item height

- CHANGELOG.MD
- lib/BlocksController.php
- lib/Roles.php
Adds caps to editors and authors.
Needed for Lunch Menu plugin
Local and stage
> TMS-962: Add Lunch Menus plugin caps to roles.

- CHANGELOG.MD
- lib/ACF/DynamicEventGroup.php
Severa-kuvaus: TMS-1009 Muumimuseo.fi Liput ja aukioloajat ruotsinkielistä sivua ei pääse päivittämään
Task: https://hiondigital.atlassian.net/browse/TMS-1009
Add an if-statement for fi & en languages, since Eventz throws an error with other languages.
> TMS-1009: Fix Eventz fatal error for language versions

- CHANGELOG.MD
- lib/ACF/DynamicEventGroup.php
- lib/Traits/EnrichPost.php
- models/single.php
- partials/single.dust
Severa-kuvaus: TMS-1017 Drupalista tulevan uutisen pääkuvapaikan kuvan alt-teksti puuttuu
Task: https://hiondigital.atlassian.net/browse/TMS-1017
Add api-images alternative text to the news main-image if found
> TMS-1017: Add image alt-text to imported news

- CHANGELOG.MD
- lib/Eventz.php
- lib/Formatters/EventzFormatter.php
Severa-kuvaus: CSD-838 Useiden integroitujen tapahtumien tapahtuma-ajat vääriä wp-sivustolla
Task: https://hiondigital.atlassian.net/browse/CSD-838
(original task TMS-1013)
Additions:
- Hide past dates in single event page
Fixes:
- Eventz.php
- Fix weekly date loop if event has multiple days in entries
- Sort entry date-array
- EventzFormatter.php
- Fix checking for recurring event arrays
> TMS-1013: Event entry fixes

- CHANGELOG.MD
- lib/Formatters/EventzFormatter.php
Severa-kuvaus: TMS-1031 Manuaaliset toistuvat tapahtumat, väärät kellonajat tapahtumanostossa
Task: https://hiondigital.atlassian.net/browse/TMS-1031
Replace strtotime with DateTime objects to prevent problems with timezone
> TMS-1031: Fix event-component recurring manual-event dates

- CHANGELOG.MD
- assets/styles/layouts/_hero-museum.scss
- assets/styles/layouts/index.scss
- lib/ACF/Fields/HeroMuseumFields.php
- lib/ACF/Fields/Settings/ThemeColorTab.php
- lib/ACF/FrontPageGroup.php
- lib/ACF/Layouts/HeroMuseumLayout.php
- lib/Formatters/HeroMuseumFormatter.php
- partials/layouts/layout-hero-museum.dust
Severa-kuvaus: TMS-1033 Taidevaltakunta-sivustolle omanlainen heroelementti
Task: https://hiondigital.atlassian.net/browse/TMS-1033
Added museum-theme style hero as an optional component
> TMS-1033: Add new optional hero-museum component

- CHANGELOG.MD
- partials/shared/contact-item.dust
Severa-kuvaus: TMS-1055 Yhteystietojen mailto-linkki ei toimi
Task: https://hiondigital.atlassian.net/browse/TMS-1055
Fix mailto-links escaping-filter
> TMS-1055: Fix mailto-links escaping-filter

- CHANGELOG.MD
- lib/ACF/Fields/HeroFields.php
- partials/layouts/layout-hero.dust
Severa-kuvaus: TMS-1061 Herossa video ei lähde pyörimään
Task: https://hiondigital.atlassian.net/browse/TMS-1061
Change hero video-field from URL to File
> TMS-1061: Change hero video-field from URL to File

- CHANGELOG.MD
- lib/Formatters/ImageGalleryFormatter.php
Severa-kuvaus: TMS-1075 Redipress 2 päivitys
Task: https://hiondigital.atlassian.net/browse/TMS-1075
Add an early return to prevent fatal error while indexing posts
> TMS-1075-fix: Early return added to ImageGalleryFormatter

- CHANGELOG.MD
- lib/Formatters/EventzFormatter.php
- models/page-events-calendar.php
Severa-kuvaus: TMS-1089 Muumimuseon viikkokalenteritapahtumat eivät näy etusivulla
Task: https://hiondigital.atlassian.net/browse/TMS-1089
Fix event fetching for events-component.
The previous code was fetching the specific amount of events that are selected to be shown on the component, which caused it to show wrong events, since some recurring events weren't fetched. Recurring events are handled after the initial fetch from the API.
> TMS-1089: Fix event fetching for events-component

- CHANGELOG.MD
- lib/ACF/Fields/CallToActionFields.php
- lib/ACF/Fields/ContentColumnsFields.php
Severa-kuvaus: TMS-1109 Lihavointi ja kursivointi mahdolliseksi kolmeen komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-TMS-1109
Change content-columns (Palstat) & call-to-action (Manuaaliset nostot) components TextAreas to Wysiwyg-fields
> TMS-1109: Change ContentColumns & CallToAction TextArea fields to Wysiwyg

- CHANGELOG.MD
- assets/assets_test.html
- assets/scripts/theme-haive.js
- assets/styles/theme-haive.scss
- assets/styles/themes/_theme-haive-overrides.scss
- lib/ACF/Fields/Settings/ThemeColorTab.php
- webpack.config.js
Severa-kuvaus: TMS-1108 Uusi värimaailmavaihtoehto kampanja- ja opetuskäytön blogiteemaan
Task: https://hiondigital.atlassian.net/browse/TMS-1108
Add new Häive color theme
> TMS-1108: Add new Häive color-theme

- CHANGELOG.MD
- partials/ui/menu/fly-out-nav.dust
Severa-kuvaus: TMS-1155 Saavutettavuus: Päävalikon alavalikoiden semanttiset puutteet
Task: https://hiondigital.atlassian.net/browse/TMS-1155
Add missing data to partial for sr-text fix
> TMS-1155: Fix screen-reader text for mobile-nav dropdowns

- CHANGELOG.MD
- lib/ACF/Fields/VideoFields.php
- partials/blocks/block-video.dust
Projekti: Tampereen kaupunki, konsernihallinto / Tietohallintoyksikkö: Tampere multisite support
Tiketin kuvaus: TMS-1201 Uusi Quickchannel-alusta sallituksi videolohkoon ja -komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-1201
Add new field for video-component that enables an iframe-video to be embedded.
> TMS-1201: Add iframe-field for video fields
