devgeniem/tms-theme-base

CHANGELOG.MD
assets/styles/base/_typography.scss
assets/styles/settings/_settings.scss
assets/styles/utils/_text-color.scss
assets/styles/utils/index.scss
lib/ACF/Fields/KeyFiguresFields.php
lib/Blocks/ImageBannerBlock.php
lib/Blocks/KeyFiguresBlock.php
lib/BlocksController.php
partials/blocks/block-image-banner.dust
partials/blocks/block-key-figures.dust
partials/layouts/layout-image-banner.dust

Add Key Figures ACF Block
[TMS-38](https://geniemdev.atlassian.net/secure/RapidBoard.jspa?rapidView=609&modal=detail&selectedIssue=TMS-38)

TMS-38: Key Figures block

---

CHANGELOG.MD
assets/styles/utils/_flex.scss
assets/styles/utils/_keep-vertical-spacing.scss
assets/styles/utils/index.scss
lib/ACF/Fields/CallToActionFields.php
lib/ACF/Layouts/CallToActionLayout.php
lib/ACF/PageGroup.php
lib/FormatterController.php
lib/Formatters/CallToActionFormatter.php
lib/Interfaces/Formatter.php
lib/ThemeController.php
partials/layouts/layout-call-to-action.dust

Add Call to Action ACF layout and Formatter functionality for Layouts and Blocks
[TMS-27](https://geniemdev.atlassian.net/browse/TMS-27)

TMS-27: Call to Action Layout

---

CHANGELOG.MD
assets/styles/ui-components/_content-grid.scss
assets/styles/ui-components/index.scss
assets/styles/utils/_wrappers.scss
assets/styles/utils/index.scss
lib/ACF/Fields/LinkListFields.php
lib/ACF/Fields/QuoteFields.php
lib/Blocks/QuoteBlock.php
lib/BlocksController.php
partials/blocks/block-image-banner.dust
partials/blocks/block-key-figures.dust
partials/blocks/block-link-list.dust
partials/blocks/block-quote.dust
partials/page.dust

Quote Block
[TMS-34](https://geniemdev.atlassian.net/browse/TMS-34)

TMS-34: Quote Block

---

CHANGELOG.MD
assets/styles/utils/_flex.scss
lib/ACF/Fields/ContentColumnsFields.php
lib/ACF/Layouts/AccordionImageLayout.php
lib/ACF/Layouts/AccordionTableLayout.php
lib/ACF/Layouts/AccordionVideoLayout.php
lib/ACF/Layouts/AccordionWysiwygLayout.php
lib/ACF/Layouts/CallToActionLayout.php
lib/ACF/Layouts/ContentColumnsLayout.php
lib/ACF/Layouts/ImageBannerLayout.php
lib/ACF/PageGroup.php
lib/BlocksController.php
lib/Formatters/ContentColumnsFormatter.php
partials/layouts/layout-content-columns.dust

Content Columns ACF Layout
[TMS-39](https://geniemdev.atlassian.net/browse/TMS-39)

TMS-39: Content Columns Layout

---

assets/scripts/fonts.js
partials/blocks/block-quote.dust

TMS-34-1: Use correct fonts

---

CHANGELOG.MD
assets/scripts/map-layout.js
assets/scripts/theme.js
assets/styles/ui-components/_embed-container.scss
assets/styles/utils/_positioning.scss
assets/styles/utils/_transform.scss
lib/ACF/Fields/MapFields.php
lib/ACF/Layouts/MapLayout.php
lib/ACF/PageGroup.php
lib/ACF/SettingsGroup.php
lib/Formatters/MapFormatter.php
partials/layouts/layout-map.dust

TMS-45: Map Layout

---

partials/layouts/layout-logo-wall.dust

Fix for TMS-28. Was missing header text and had wrong background colors.

TMS-28-1: Header text and background color

---

CHANGELOG.MD
lib/ACF/Field/TextEditor.php
lib/ACF/Fields/LinkListFields.php
lib/ACF/Fields/MapFields.php
lib/ACF/Layouts/AccordionWysiwygLayout.php
lib/ACFController.php
lib/Admin.php

Wysiwyg with selected toolbar items.
Also adds `tms-minimal` toolbar layout and gets used where applicable.
TMS-75
Used in AccordionWysiwygLayout.

TMS-75: Text Editor

---

CHANGELOG.MD
lib/ACF/Fields/TextBlockFields.php
lib/ACF/FrontPageGroup.php
lib/ACF/Layouts/TextBlockLayout.php
lib/ACF/PageGroup.php
partials/layouts/layout-textblock.dust

Text block layout.
Build on top of #50. It should be reviewed and merged first.
TMS-73

TMS-73: Text block (Layout)

---

CHANGELOG.MD
lib/ACF/SettingsGroup.php
models/error404.php
partials/error404.dust

TMS-58: Error 404 page

---

assets/icons/checkmark.svg
assets/icons/index.js
assets/styles/settings/brand/_colors.scss
assets/styles/ui-components/_pagination.scss
assets/styles/ui-components/_pill.scss
assets/styles/ui-components/index.scss
lib/DustPressController.php
models/strings.php
partials/ui/button-search-submit.dust
partials/ui/input-text.dust
partials/ui/pagination.dust
partials/ui/password_form.dust

TMS-57: Materials page

---

CHANGELOG.MD
lib/ACF/PostGroup.php

TMS-66: Add articles fields

---

assets/styles/settings/_settings.scss
lib/ACF/Fields/HeroFields.php
lib/ACF/PageGroup.php
lib/ACF/PostGroup.php
lib/Formatters/ImageFormatter.php
lib/Images.php
lib/Taxonomy/Category.php
lib/Taxonomy/PostTag.php
lib/ThemeSupports.php
models/single.php
models/strings.php
partials/single.dust
partials/views/single/single-meta.dust
partials/views/single/single-related.dust

TMS-67-1: Add single view

---

CHANGELOG.MD
assets/scripts/home.js
assets/scripts/theme.js
assets/styles/ui-components/_pagination.scss
lib/ACF/HomeGroup.php
lib/ACF/PageGroup.php
lib/ACF/SettingsGroup.php
lib/Taxonomy/Category.php
lib/ThemeController.php
lib/ThemeSupports.php
models/archive.php
models/home.php
models/strings.php
partials/home.dust
partials/views/home/home-filters.dust
partials/views/home/home-grid-item.dust
partials/views/home/home-highlight.dust
partials/views/home/home-list-item.dust

TMS-68: Add archive view

---

CHANGELOG.MD
assets/styles/helpers/_button.scss
lib/ACF/FrontPageGroup.php
lib/ACF/Layouts/GridLayout.php
lib/ACF/PageGroup.php
lib/Formatters/GridFormatter.php
partials/layouts/layout-grid.dust

TMS-89: Add layout grid

---

CHANGELOG.MD
lib/ACF/SettingsGroup.php
models/shared/header.php
partials/shared/header-brand.dust
partials/shared/header-inner.dust
partials/shared/header.dust

Add "hide search" to settings
TMS-101

TMS-101: Hide search settings

---

CHANGELOG.MD
assets/scripts/main.js
assets/scripts/theme-tummavesi.js
assets/scripts/theme-tunnelma.js
assets/styles/_bulma.scss
assets/styles/_theme-header.scss
assets/styles/base/index.scss
assets/styles/helpers/_button.scss
assets/styles/helpers/_color.scss
assets/styles/main.scss
assets/styles/settings/_settings.scss
assets/styles/settings/brand/_colors.scss
assets/styles/theme-tummavesi.scss
assets/styles/theme-tunnelma.scss
assets/styles/themes/_includes.scss
assets/styles/utils/_background.scss
lib/Assets.php
webpack.config.js

Adds possibility to create and generate multiple color themes.
TMS-97

TMS-97: Generate multiple themes

---

CHANGELOG.MD
lib/NavigationController.php
lib/ThemeSupports.php

- Disable Gutenberg colors and fonts
- Hide custom links from navigation
TMS-102

TMS-102-editor: Admin tweaks

---

CHANGELOG.MD
models/error404.php
models/shared/header.php

Hide search button from 404 if it is hidden from Site Settings.
TMS-102

TMS-102: Add check Display Search setting

---

CHANGELOG.MD
lib/Traits/Breadcrumbs.php

Removed home icon from breadcrumbs.
Client request.

Removed home icon from breadcrumbs

---

CHANGELOG.MD
partials/blocks/block-quote.dust
partials/shared/header-inner.dust

TMS-102-1: Minor fixes

---

CHANGELOG.MD
models/shared/header.php
partials/shared/header-inner.dust

TMS-102: Minor bugfixes

---

lib/ACF/SettingsGroup.php
lib/Blocks/AccordionBlock.php
lib/Blocks/KeyFiguresBlock.php
lib/Blocks/ShareLinksBlock.php
lib/Blocks/TableBlock.php
lib/Formatters/AccordionTableFormatter.php
lib/Images.php
lib/Roles.php
models/archive.php
models/home.php

Fix lint warnings

---

CHANGELOG.MD
assets/styles/helpers/_button.scss
assets/styles/helpers/_color.scss

Fixes to `.button` styles.
Build on top of #85 
Button generation was over-engineered, this helps bring it back a bit.
See `assets/assets_test.html`

TMS-97: Fix button styles

---

CHANGELOG.MD
partials/ui/sibling-navigation.dust

Fix sibling page navigation link href.

TMS-102-3: Fix sibling navigation href

---

CHANGELOG.MD
lib/ACF/Fields/ArticlesFields.php
lib/PostType/Post.php

Remove character limit when displaying excerpts.
TMS-102

TMS-102-4: Remove excerpt character limit

---

models/single-blog-article.php

Fix blog article related posts.

Fix blog-article related posts query taxonomy

---

lib/Traits/EnrichPost.php

Remove character limit when displaying excerpts

Remove character limit when displaying excerpts

---

assets/scripts/toggle.js
assets/styles/helpers/_button.scss
assets/styles/ui-components/_pill.scss
assets/styles/ui-components/header/_fly-out-nav.scss
assets/styles/ui-components/header/_language-nav.scss
assets/styles/ui-components/header/_primary-nav.scss
assets/styles/ui-components/header/_secondary-nav.scss
lib/Formatters/GridFormatter.php
partials/shared/header-search-toggle.dust
partials/shared/header.dust
partials/ui/button-toggle.dust
partials/ui/menu/menu-item-dropdown.dust
partials/views/single-blog-article/blog-info.dust

Design review changeset #1.
TMS-155

Design Review #1

---

assets/scripts/toggle.js
assets/styles/helpers/_button.scss
assets/styles/layouts/_icon-links.scss
assets/styles/settings/brand/_typography.scss
assets/styles/ui-components/_footer.scss
assets/styles/ui-components/_highlight-article.scss
assets/styles/ui-components/_pill.scss
assets/styles/ui-components/header/_fly-out-nav.scss
assets/styles/ui-components/header/_language-nav.scss
assets/styles/ui-components/header/_primary-nav.scss
assets/styles/ui-components/header/_secondary-nav.scss
lib/Formatters/GridFormatter.php
partials/layouts/layout-events.dust
partials/layouts/layout-icon-links.dust
partials/shared/footer-inner.dust
partials/shared/header-search-toggle.dust
partials/shared/header.dust
partials/ui/button-toggle.dust
partials/ui/image/image-block__meta.dust
partials/ui/menu/menu-item-dropdown.dust
partials/views/home/home-highlight.dust
partials/views/single-blog-article/blog-info.dust

Design review changeset #2.
TMS-155

Design Review #2

---

assets/scripts/modal.js
assets/scripts/toggle.js
assets/styles/blocks/custom/_grid.scss
assets/styles/blocks/custom/_image-gallery.scss
assets/styles/helpers/_button.scss
assets/styles/layouts/_icon-links.scss
assets/styles/settings/brand/_typography.scss
assets/styles/ui-components/_footer.scss
assets/styles/ui-components/_highlight-article.scss
assets/styles/ui-components/_pill.scss
assets/styles/ui-components/_slide-deck.scss
assets/styles/ui-components/header/_fly-out-nav.scss
assets/styles/ui-components/header/_language-nav.scss
assets/styles/ui-components/header/_primary-nav.scss
assets/styles/ui-components/header/_secondary-nav.scss
lib/Formatters/GridFormatter.php
partials/blocks/block-grid-item--featured.dust
partials/blocks/block-grid-item.dust
partials/blocks/block-key-figures.dust
partials/blocks/block-quote.dust
partials/layouts/layout-events.dust
partials/layouts/layout-icon-links.dust
partials/shared/footer-inner.dust
partials/shared/header-search-toggle.dust
partials/shared/header.dust
partials/ui/button-toggle.dust
partials/ui/image/image-block__meta.dust
partials/ui/menu/menu-item-dropdown.dust
partials/views/home/home-highlight.dust
partials/views/single-blog-article/blog-info.dust

Design review changeset #3.
TMS-155

Design Review #3

---

partials/ui/menu/menu-item-dropdown.dust
partials/ui/menu/menu-item.dust

Fix navigation item duplicate ids

a11y: Fix navigation item duplicate ids

---

partials/shared/header.dust

Make sure the "Skip to content" -link is the first element to be focused.

a11y: Skip to content link

---

assets/styles/ui-components/header/_primary-nav.scss
partials/shared/header-inner.dust
partials/ui/menu/menu-item-dropdown.dust
partials/ui/menu/menu-item-single.dust
partials/ui/menu/menu-item.dust

Fix navigation element hierarchy by changing `<ul> > <div>` into a `<ul> > <li>` where applicable.

Fix nav element hierarchy

---

assets/styles/layouts/_image-banner.scss
assets/styles/layouts/index.scss
assets/styles/ui-components/_icon.scss
assets/styles/ui-components/header/_notice.scss
assets/styles/utils/_transform.scss
lib/ACF/FrontPageGroup.php
models/single-blog-article.php
models/single.php
partials/layouts/layout-sitemap.dust
partials/shared/header-notice.dust
partials/shared/map-embed.dust
partials/ui/share-links.dust

Design review changeset #4.
TMS-155

Design Review #4

---

CHANGELOG.MD
lib/ACF/Fields/ThemeColorTab.php
lib/Formatters/GridFormatter.php
lib/Images.php
lib/Traits/EnrichPost.php
models/single-blog-article.php
models/single.php

Design review #5 - Add Default Content Image setting
TMS-155

DR-5: Add Default Content Image setting

---

functions.php
lib/Constants.php
lib/PostTypeController.php
lib/ThemeController.php

Modify functionality for child themes
TMS-192

TMS-192: Modify functionality for child themes

---

CHANGELOG.MD
assets/styles/base/_typography.scss
assets/styles/ui-components/_pill.scss
assets/styles/utils/_background.scss
lib/ACFController.php
lib/Assets.php
lib/Formatters/EventsFormatter.php
lib/Localization.php
lib/TaxonomyController.php
lib/Traits/Sharing.php
models/error404.php
models/page-event.php
models/page-events-calendar.php
models/page-extend.php
models/page.php
partials/layouts/layout-events.dust
partials/page-event.dust
partials/page-events-calendar.dust
partials/shared/footer-back-to-top.dust
partials/shared/footer-inner.dust
partials/ui/button-search-submit.dust
partials/ui/share-links.dust
partials/views/page-events-calendar/page-events-calendar-item-grid.dust
partials/views/page-events-calendar/page-events-calendar-item-list.dust
partials/views/page/page-hero.dust
partials/views/single-dynamic-event/single-dynamic-event-group-title.dust
partials/views/single-dynamic-event/single-dynamic-event-hero-meta.dust
partials/views/single-dynamic-event/single-dynamic-event-info.dust

Adds filters for overriding assets & template classes.
TMS-192

TMS-192-1: Add filters for assets

---

CHANGELOG.MD
lib/ACF/Layouts/CallToActionLayout.php
partials/layouts/layout-call-to-action.dust

Add filters to Call to Action layout
TMS-141

TMS-141: Add filters to Call to Action layout

---

lib/ACF/DynamicEventGroup.php
lib/ACF/FrontPageGroup.php
lib/ACF/OnepagerGroup.php
lib/ACF/PageGroup.php
lib/ACF/PostGroup.php

Add group key to filter params
TMS-138

TMS-138: Add group key to filter params

---

CHANGELOG.MD
assets/styles/utils/_border.scss
assets/styles/utils/_images.scss
assets/styles/utils/index.scss
lib/Traits/Breadcrumbs.php
models/strings.php
partials/blocks/block-share-links.dust
partials/single-blog-article.dust
partials/single.dust
partials/ui/share-links.dust

Add support for artist view.
TMS-133.

TMS-133: Artist

---

assets/styles/theme-havu.scss
assets/styles/theme-kokemus.scss
assets/styles/theme-neutraali.scss
assets/styles/theme-paahde.scss
assets/styles/theme-tummavesi.scss
assets/styles/theme-tunnelma.scss
assets/styles/theme-tyo.scss

Add missing accent color
TMS-102

TMS-102-6: Add missing accent color

---

partials/shared/footer-back-to-top.dust
partials/shared/map-embed.dust
partials/ui/button-link.dust

Fix buttons text wrap in iOS 
TMS-199

TMS-199: Fix button text wrapping in iOS 

---

CHANGELOG.MD
assets/scripts/copy-to-clipboard.js

Renamed branch from #157
Bug fix, TMS-207

TMS-207: Fixes copy to clipboard event target

---

CHANGELOG.MD
lib/Blocks/ShareLinksBlock.php

TMS-102-0909: Add link classes to share links block

---

CHANGELOG.MD
lib/Constants.php

Enable RediPress MySQL fallback by default.

Feature: Enable redipress MySQL fallback

---

CHANGELOG.MD
lib/ACF/PageEventsCalendarGroup.php
models/page-events-calendar.php
partials/page-events-calendar.dust

Adds description field to Event Calender page template.
TMS-220

TMS-220: Event Calendar template description field

---

CHANGELOG.MD
models/page-event.php
partials/page-event.dust

Add share buttons to Event page template
TMS-203
TMS-10

TMS-203: Add share buttons to Event page template

---

CHANGELOG.MD
assets/styles/helpers/_color.scss
assets/styles/ui-components/_pill.scss
assets/styles/views/_search.scss
assets/styles/views/index.scss
models/search.php
partials/archive-blog-article.dust
partials/home.dust
partials/search.dust
partials/views/home/home-list-item.dust
partials/views/page-events-calendar/page-events-calendar-item-list.dust
partials/views/search/results.dust
partials/views/search/search-item-meta.dust

Adds search results functionality
TMS-213
TMS-10

TMS-213: Search results

---

CHANGELOG.MD
lib/Roles.php

Adds `view_stream` capability to `super_administrator` role.
TMS-163 (CR: TMS-10)

TMS-163: Allow Stream logs to Super Administrators

---

CHANGELOG.MD
assets/styles/blocks/custom/_accordion.scss
assets/styles/blocks/custom/_grid.scss
assets/styles/blocks/custom/_subpages.scss
assets/styles/helpers/_button.scss
assets/styles/ui-components/_footer.scss
lib/Blocks/KeyFiguresBlock.php
lib/Formatters/GridFormatter.php
lib/Formatters/IconLinksFormatter.php
partials/blocks/block-accordion.dust
partials/blocks/block-image-banner.dust
partials/blocks/block-notice-banner.dust
partials/layouts/layout-icon-links.dust
partials/ui/button-link.dust
partials/ui/icon.dust

TMS-318: Accessibility fixes

---

CHANGELOG.MD
models/shared/header.php

Fix search form action
TMS-363

TMS-363: Fix search form action

---

CHANGELOG.MD
models/shared/header.php
models/strings.php
partials/blocks/block-subpages.dust
partials/shared/header-inner.dust
partials/shared/header-logo.dust
partials/ui/menu/menu-item-dropdown.dust
partials/ui/menu/menu-item.dust

Add screen reader texts
TMS-318

TMS-318-1: Add screen reader texts

---

CHANGELOG.MD
partials/views/page-events-search/form.dust

TMS-374: Fix event search form styles

---

CHANGELOG.MD
partials/shared/footer-inner.dust

CR: [https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
is-block class to footer's logo link
[TMS-381](https://geniemdev.atlassian.net/browse/TMS-381)
Locally and staging

TMS-381: Fix footer's logo link

---

CHANGELOG.MD
lib/Traits/Links.php
models/search.php
models/shared/header.php

Fix search action link when changing language
TMS-387

TMS-387: Fix search action link when changing language

---

CHANGELOG.MD
assets/styles/views/_single-blog-article.scss

TMS-388: Fix blog info layout

---

CHANGELOG.MD
assets/styles/helpers/_checkradio.sass

TMS-398: Fix checkbox styles

---

CHANGELOG.MD
assets/scripts/external-links.js

Display external link icons
TMS-339

TMS-339: Dispay external link icons

---

CHANGELOG.MD
assets/styles/ui-components/header/_fly-out-nav.scss
assets/styles/ui-components/header/_primary-nav.scss
package-lock.json

CR: [https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Fix current menu parent underlining in mobile and desktop.
[TMS-401](https://geniemdev.atlassian.net/browse/TMS-401)

TMS-401: Fix nav underlining for current menu parent

---

CHANGELOG.MD
partials/page.dust

Fix spacing for pages without hero and breadcrumb.
[TMS-402](https://geniemdev.atlassian.net/browse/TMS-402)
Locally, staging as much as possible.

TMS-402: Conditions for spacing in page template if has hero and breadcrumbs

---

CHANGELOG.MD
lib/Roles.php

Add unfiltered html capability to author and editor role. Works in other themes also.
[TMS-406](https://geniemdev.atlassian.net/browse/TMS-406)
Locally and staging, different sites.

TMS-406: Add unfiltered html capability to author and editor role

---

CHANGELOG.MD
assets/scripts/hero.js
partials/layouts/layout-hero.dust

Allow video to be used with keyboard
TMS-410

TMS-410: Allow video to used with keyboard

---

CHANGELOG.MD
assets/styles/ui-components/_footer.scss
partials/shared/footer-inner.dust

Tampere logo focus styles
TMS-413

TMS-413: Tampere logo focus styles

---

lib/ACF/BlogArticleGroup.php

redipress_queryable_filter added for getting Blog Articles in search results when searching by Blog Author names.
[TMS-407](https://geniemdev.atlassian.net/browse/TMS-407)

TMS-407-2: Blog Articles are included in search results when searching by Blog Authors name

---

CHANGELOG.MD
lib/Formatters/ImageFormatter.php
partials/layouts/layout-call-to-action.dust
partials/layouts/layout-content-columns.dust

Layouts call to action and content columns use author name instead of artist name
[TMS-409](https://geniemdev.atlassian.net/browse/TMS-409)

TMS-409: Layouts call to action and content columns use author name instead of artist name

---

CHANGELOG.MD
assets/styles/themes/_theme-neutraali-overrides.scss
assets/styles/ui-components/_pill.scss

Fix active pill hover colors
TMS-477

TMS-477: Fix active pill hover colors

---

CHANGELOG.MD
models/strings.php
partials/layouts/layout-hero.dust

Add aria labels for hero video controls
TMS-478

TMS-478: Add aria labels for hero video controls

---

CHANGELOG.MD
assets/scripts/common.js
assets/scripts/external-links.js
assets/scripts/image-carousel.js
assets/styles/ui-components/_modal.scss
partials/blocks/block-image-gallery.dust
partials/layouts/layout-image-carousel.dust

- Image carousel modal
- External link icon 
- Img title swiched from description to alt text in image gallery
[TMS-481](https://geniemdev.atlassian.net/browse/TMS-481)
Locally, staging with Voice Over + Safari and Chrome

TMS-481: Fix accesssibility for screenreaders in image, gallery and slick slider in modal

---

CHANGELOG.MD
assets/styles/ui-components/_modaal.scss
lib/Blocks/ImageBannerBlock.php
lib/Formatters/EventsFormatter.php
lib/Formatters/GridFormatter.php
models/single.php
partials/layouts/layout-events.dust
partials/ui/image/image-block__meta.dust

Additional filters and miscellaneous theme fixes.
TMS-420

TMS-420: Additional filters and miscellaneous theme fixes

---

CHANGELOG.MD
partials/page.dust
partials/ui/entry-title.dust

Page title in separate template for overriding in child theme
[TMS-843](https://geniemdev.atlassian.net/browse/TMS-483)

TMS 483 – Page title template for overriding in child theme

---

lib/Formatters/IconLinksFormatter.php
partials/layouts/layout-articles-inner.dust
partials/views/single/single-related.dust

TMS-421-layouts

---

CHANGELOG.MD
lib/Formatters/EventsFormatter.php
lib/PostType/DynamicEvent.php
partials/ui/event-highlight.dust

Add language param to API queries

fix/event-lang: Add language param to API queries

---

CHANGELOG.MD
assets/styles/ui-components/_cookiebot.scss
assets/styles/ui-components/index.scss
lib/Cookiebot.php
lib/ThemeController.php

Cookiebot setup for base theme and child themes
TMS-366

Tms 366: Cookiebot setup

---

CHANGELOG.MD
assets/scripts/sitemap.js
assets/styles/layouts/_sitemap.scss

Adjust sitemap button styles
TMS-561

TMS-561: Adjust sitemap button styles

---

CHANGELOG.MD
lib/Formatters/ImageFormatter.php
partials/ui/image/image-block__meta.dust

Image metadata formatting. 
TMS-564
Locally

Tms 564: Image metadata formatting 

---

CHANGELOG.MD
lib/Traits/EnrichPost.php

Use mb_substr for special character support support
TMS-567

TMS-567: Use mb_substr for special character support support

---

CHANGELOG.MD
models/search.php

TMS-573: Escape search query

---

CHANGELOG.MD
partials/single-dynamic-event-cpt.dust

TMS-562: Adjust layout

---

CHANGELOG.MD
partials/ui/image/image-block__meta.dust

Fix issue where image title text was not displayed if image has no caption
TMS-576

TMS-576: Fix issue where image title text was not displayed if image has no caption

---

CHANGELOG.MD
lib/Formatters/ImageFormatter.php

Don't display image author text in artist text
TMS-576

TMS-576: Don't display image author text in artist text

---

CHANGELOG.MD
assets/scripts/common.js
assets/scripts/header.js
assets/styles/ui-components/header/_notice.scss
lib/ThemeSupports.php
partials/shared/header.dust

Do not cache notice banner open / closed state
TMS-568

TMS-568: Do not cache notice banner closed state

---

CHANGELOG.MD
lib/Traits/EnrichPost.php

Display hellip on the end of stripped excerpts
TMS-572

TMS-572: Excerpt hellip

---

CHANGELOG.MD
models/page-event.php

Add og-tags for events
TMS-565

TMS-565: Add og-tags for events

---

CHANGELOG.MD
lib/Traits/Breadcrumbs.php

Fix breadcrumb trail for articles and blogs
TMS-494

TMS-494: Breadcrumbs for articles and blogs

---

CHANGELOG.MD
partials/shared/header.dust

TMS-582
Run custom scripts after wp_head

TMS-582: Run custom scripts after wp_head

---

CHANGELOG.MD
assets/scripts/header.js

Fix issue where user was unable to close fly out navigation in mobile

Fix issue where user was unable to close fly out navigation in mobile

---

CHANGELOG.MD
assets/scripts/header.js
package-lock.json
package.json
partials/shared/header.dust

- Revert "Downgrade image-webpack-loader"
- Alternative fix to hamburber nav toggle

Fix/mobile-nav: Fix hamburger menu toggle, attempt #2

---

CHANGELOG.MD
assets/scripts/modal.js
assets/scripts/primary-nav.js
assets/scripts/theme.js

When clicking somewhere else than nav, all nav's dropdows closes
TMS-419

TMS-419: Clicking outside nav closes it's dropdowns

---

CHANGELOG.MD
assets/styles/ui-components/header/_fly-out-nav.scss
assets/styles/ui-components/header/_language-nav.scss
models/shared/header.php
partials/shared/header-inner.dust
partials/ui/menu/language-nav-dropdown.dust

Add filters & variables for language nav customization
TMS-492

TMS-492: Add filters & variables for language nav customization

---

CHANGELOG.MD
lib/Security.php

Disable user list and detail REST endpoints
TMS-631

TMS-631: Disable user list REST endpoints

---

CHANGELOG.MD
lib/Formatters/SubpagesFormatter.php

CR: https://geniemdev.atlassian.net/browse/TMS-626
Subpages of this page lists primarily by menu order and secondarily by post date
TMS-525
Local, staging

TMS-525: Subpages' orderby parameters

---

CHANGELOG.MD
assets/scripts/accordion.js
assets/scripts/table.js
assets/styles/ui-components/_table.scss

CR: https://geniemdev.atlassian.net/browse/TMS-626
Indicate works with tables in accordions. Tables can be scrolled with keyboard.
TMS-522
Local, staging

TMS-522: Indicate in tables

---

CHANGELOG.MD
lib/BlocksController.php

CR: https://geniemdev.atlassian.net/browse/TMS-626
Added notice banner block for dynamic event content type
TMS-540
Local, staging

TMS-540: Notice banner for dynamic event

---

assets/scripts/header.js

Fix fly out nav height
TMS-638

TMS-638: Fix fly out nav height

---

CHANGELOG.MD
lib/Admin.php

CR: https://geniemdev.atlassian.net/browse/TMS-626
Filter added for restricting Gravity Form's available fields.
TMS-534
Local, staging

TMS-534-2: Gravity form available fields

---

CHANGELOG.MD
lib/Roles.php

CR: ??
Authors now have Table Press caps
https://geniemdev.atlassian.net/browse/TMS-646
Local

TMS-646: TablePress caps added for author

---

assets/scripts/fly-out-nav.js
assets/styles/ui-components/header/_primary-nav.scss
models/shared/header.php

Add option to use top level menu item as a dropdown trigger only
TMS-424

TMS-424: Option for navigation dropdown trigger only

---

CHANGELOG.MD
lib/LinkedEvents.php

Force event location display to finnish 
TMS-650

TMS-650: Force event location display to finnish 

---

CHANGELOG.MD
assets/scripts/fly-out-nav.js

Fix issue with trigger only menu item child links

Fix flyout nav trigger only child links

---

assets/styles/base/_base.scss

hotfix/body-margin: Fix body margin

---

partials/ui/pagination.dust

Convert pagination hellip a into span
TMS-543

TMS-543: Convert pagination hellip a into span

---

CHANGELOG.MD
lib/GravityForms.php

Added filter to replace Gravity Form's submit input with submit button
TMS-470
Local, SH and Taidemuseo themes

TMS-470: GF submit as button

---

CHANGELOG.MD
assets/scripts/gravity-forms-patch.js
assets/scripts/theme.js

CR: [TMS-628](http://geniemdev.atlassian.net/browse/TMS-628)
JS to fix problem with GF block's file upload. 
TMS-470
Local, stage

TMS-470-2: Patch for Gravity Forms' block multifle upload

---

CHANGELOG.MD
lib/Formatters/IconLinksFormatter.php

CR: [TMS-628](http://geniemdev.atlassian.net/browse/TMS-628)
Fix for IconLinksFormatter if key icon is not set
TMS-724
Local

TMS-724: Fix for IconLinksFormatter if key icon is not set

---

CHANGELOG.MD
assets/scripts/gravity-forms-patch.js

CR: [TMS-628](http://geniemdev.atlassian.net/browse/TMS-628)
Bugfix for case where there's multiple forms on page
TMS-470
Local, stage

TMS-470-3:  Gravity Forms file upload bugfix

---

CHANGELOG.MD
models/search.php

- [ x ] New feature (non-breaking change which adds functionality)

TMS-713: Limit search filtering for post types with posts.

---

CHANGELOG.MD
partials/layouts/layout-articles-inner.dust
partials/layouts/layout-events.dust

- [ x ] New feature (non-breaking change which adds functionality)

TMS-714: Replace events and articles layout link with button-link

---

CHANGELOG.MD
assets/styles/ui-components/_content-grid.scss
lib/ACF/Fields/TextBlockFields.php
lib/Formatters/TextBlockFormatter.php
partials/layouts/layout-textblock.dust

TMS-712: Add fields to TextBlockLayout

---

CHANGELOG.MD
lib/ACF/FrontPageGroup.php
lib/ACF/Layouts/ShareLinksLayout.php
lib/ACF/PageGroup.php
lib/Blocks/ShareLinksBlock.php
lib/Formatters/ShareLinksFormatter.php
partials/layouts/layout-share-links.dust

TMS-715: Add ShareLinksLayout

---

CHANGELOG.MD
lib/ACF/Fields/EventsFields.php
lib/Formatters/EventsFormatter.php
models/page-events-search.php
theme.json

TMS-726: Add order option

---

CHANGELOG.MD
lib/ACF/Fields/ImageCarouselFields.php
lib/Formatters/ImageCarouselFormatter.php

TMS-304-1: Set min amount of images in carousel to 4 and prevent displaying if not at least 4 images added.

---

lib/Integrations/Tampere/ApiController.php
lib/Integrations/Tampere/PersonApiController.php
lib/Integrations/Tampere/PlaceOfBusinessApiController.php

Adds abstract base class for API controllers and implementations
for Person and Place of Business endpoints
TMS-225

TMS-225: Add API Controllers for Tampere API

---

CHANGELOG.MD
lib/ACF/Fields/Settings/ExceptionNoticeSettingsTab.php
models/shared/header.php
partials/shared/header-notice.dust

TMS-718: Add cta-button to exception notice

---

CHANGELOG.MD
lib/ACF/Fields/Settings/ArchiveSettingsTab.php
models/archive.php
partials/views/home/home-filters.dust
partials/views/home/home-grid-item.dust
partials/views/home/home-list-item.dust

TMS-732: Add option to hide categories in archive page.

---

CHANGELOG.MD
lib/ThemeSupports.php

Add default image filter
TMS-760

TMS-760: Add default image filter

---

CHANGELOG.MD
models/archive.php
models/home.php

Hide categories in Home class and in its' ancestors
TMS-763

TMS-763: Hide categories in Home class and in its' descendants

---

assets/scripts/countdown.js

Cast value to int
Fixes a bug in TMS-756

TMS-756: Parse value to integer

---

CHANGELOG.MD
partials/layouts/layout-call-to-action.dust

Fix displaying of image author on Call to Action
TMS-766

TMS-766: Fix displaying of image author on Call to Action

---

CHANGELOG.MD
assets/styles/blocks/custom/_countdown.scss
partials/blocks/block-countdown.dust

Fix block countdown colors in certain color schemes
TMS-769

TMS-769: Fix block countdown colors in certain color schemes

---

partials/blocks/block-image-gallery.dust

Fix image clickable option
TMS-694

Fix image clickable option

---

CHANGELOG.MD
lib/NavigationController.php

Add filter for custom links removal.
TMS-771
Local, stage.

TMS-771: Add filter for custom links removal

---

CHANGELOG.MD
lib/ACF/Fields/Settings/ExceptionNoticeSettingsTab.php
models/shared/header.php

CR: https://geniemdev.atlassian.net/browse/TMS-783
Add filter for exception notice data.
TMS-783
Local, stage.

TMS-783: Filter for exception notice data

---

CHANGELOG.MD
lib/ACF/Fields/ContactsFields.php
lib/Integrations/Tampere/ApiController.php

Load API contacts with AJAX
TMS-223

TMS-223: Load choices with ajax

---

CHANGELOG.MD
models/home.php
partials/home.dust

Do not display No results found when Home view has a featured post
TMS-805

TMS-805: Fix no results text logic

---

CHANGELOG.MD
lib/ACF/Fields/PlaceOfBusinessFields.php

TASK: https://geniemdev.atlassian.net/browse/TMS-223 
Choices for Place of business loaded with AJAX
TMS-223
Local

TMS-223-2: Load choices with AJAX for PlaceOfBusiness

---

CHANGELOG.MD
lib/Formatters/ContactFormatter.php
lib/Integrations/Tampere/ApiController.php
lib/Integrations/Tampere/PersonApiController.php
lib/Integrations/Tampere/PersonFacade.php
models/page-contacts.php

Reduce cache size from API calls
TMS-828

TMS-828: Reduce contact cache size

---

CHANGELOG.MD
lib/Integrations/Tampere/ApiController.php

Tampere API Performance optimizations
TMS-836

TMS-836: Tampere API Performance optimizations

---

CHANGELOG.MD
lib/Formatters/EventsFormatter.php

Force sort events by end_time
TMS-840

TMS-840: Force sort events by end_time

---

CHANGELOG.MD
lib/Integrations/Tampere/ApiController.php

TMS-847: Prevent double slashes on api url

---

CHANGELOG.MD
lib/Integrations/Tampere/ApiController.php
lib/Traits/EnrichPost.php
partials/views/home/home-grid-item.dust

Show drupal image on home result card
TMS-862

TMS-862: Show drupal image on home result card

---

CHANGELOG.MD
partials/blocks/block-image-carousel.dust

TMS-793: Fix typo in carousel block

---

lib/Formatters/ContactFormatter.php

Use importer plugin

---

CHANGELOG.MD
lib/ACF/Fields/Settings/HeaderSettingsTab.php
lib/ThemeSupports.php

Add Favicon field to settings.
TMS-807

TMS-807: Add Favicon field to settings

---

partials/views/home/home-list-item.dust

TMS-880: Display drupal image on home list item

---

CHANGELOG.MD
lib/Formatters/ContactFormatter.php
partials/blocks/block-contacts.dust

Fix contacts block alignment
[TMS-845](https://geniemdev.atlassian.net/browse/TMS-845)

TMS-845: Fix contacts block alignment

---

CHANGELOG.MD
partials/views/home/home-highlight.dust

CR: https://geniemdev.atlassian.net/browse/PIEN-7427
Fix highlighted article image on articles layout
PIEN-7427
Local, stage.

PIEN-7427: Fix highlighted article image on articles layout

---

CHANGELOG.MD
lib/ACF/Fields/Settings/ChatTab.php
lib/ACF/SettingsGroup.php
models/shared/header.php
partials/shared/header.dust

TMS-891: Add chat

---

CHANGELOG.MD
models/page-contacts.php

PIEN-7508: fix drupal contacts on contact page template

---

CHANGELOG.MD
lib/EmbedController.php
lib/ThemeController.php

Add quickchannel video embed support
TMS-910

TMS-910: Add quickchannel video embed support

---

CHANGELOG.MD
lib/ACF/DynamicEventGroup.php
lib/ACF/Fields/VideoFields.php
lib/ACF/FrontPageGroup.php
lib/ACF/Layouts/VideoLayout.php
lib/ACF/OnepagerGroup.php
lib/ACF/PageGroup.php
partials/blocks/block-video.dust
partials/layouts/layout-video.dust

Add layout video embed
TMS-897

TMS-897: Add layout video embed

---

CHANGELOG.MD
lib/Formatters/ContactFormatter.php

TMS-916: Fix order of selected api contacts.

---

CHANGELOG.MD
lib/ThemeSupports.php

CR: https://geniemdev.atlassian.net/browse/PIEN-8439
Add pageId meta tag to head for Siteimprove hotlinking

PIEN-8439: Add pageID meta tag

---

CHANGELOG.MD
models/single.php
partials/views/single/single-related.dust

CR: PIEN-8524
Display API images in related articles
PIEN-8524

PIEN-8524: Display API images

---

CHANGELOG.MD
lib/Blocks/LinkListBlock.php

PIEN-8585: Check empty links

---

CHANGELOG.MD
models/single.php

CR: https://geniemdev.atlassian.net/browse/PIEN-8394
Add API image to og:image tag.
PIEN-8394

PIEN-3894: Add API image to og:image tag

---

CHANGELOG.MD
lib/Formatters/EventzFormatter.php
style.css

Task: https://hiondigital.atlassian.net/browse/TMS-973
Fix manual event sorting in event-highlight component

TMS-973: Fix manual event sorting

---

CHANGELOG.MD
assets/styles/base/_typography.scss
lib/Roles.php

Task: https://hiondigital.atlassian.net/browse/TMS-978
Add has-line-height-normal class

TMS-978: Add has-line-height-normal class

---

CHANGELOG.MD
lib/ACF/Fields/CallToActionFields.php
lib/ACF/Fields/ContentColumnsFields.php
lib/ACF/Fields/GridFields.php
lib/ACF/Fields/TextBlockFields.php

Severa-kuvaus: TMS-980 Pohjateeman komponenttien sisällön lisääminen sivuston hakutuloksiin
Task: https://hiondigital.atlassian.net/browse/TMS-980
Add redipress_include_search to components

TMS-980: Add redipress_include_search to components

---

CHANGELOG.MD
partials/shared/header-inner.dust
partials/ui/menu/language-nav.dust
partials/ui/menu/menu-item-dropdown.dust
partials/ui/menu/menu-item.dust

Severa-kuvaus: TMS-1015 Saavutettavuuskorjauksia
Task: https://hiondigital.atlassian.net/browse/TMS-1015
Fix duplicate ID for horizontal language navigation, fix escaping filters

TMS-1015: Header accessibility fixes

---

CHANGELOG.MD
lib/Eventz.php
lib/Formatters/EventzFormatter.php
lib/Traits/Sharing.php
models/page-events-search.php
partials/ui/event-highlight.dust
partials/views/single-dynamic-event/single-dynamic-event-info.dust

Severa-kuvaus: TMS-1013 Tapahtumaintegraatio: viikkokalenteri-tapahtumat
Task: https://hiondigital.atlassian.net/browse/TMS-1013
Add weekly event-entries fetching from Eventz API

TMS-1013: Add entries fetching to Eventz event-integration

---

CHANGELOG.MD
lib/Formatters/EventzFormatter.php
models/page-events-search.php
phpcs.xml

Severa-ID: 2147
Severa-kuvaus: TMS-968 Manuaaliset tapahtumat: tapahtuman toistuvuus
Task: https://hiondigital.atlassian.net/browse/TMS-968
Query events with recurring dates to event listing -component

TMS-968: Add recurring events to event-component

---

CHANGELOG.MD
assets/styles/ui-components/_modal.scss

Severa-kuvaus: TMS-1021 Kuvakarusellin vaakakuvien asemointi
Task: https://hiondigital.atlassian.net/browse/TMS-1021
Fix image alignment in image-carousel modal, prevent vertical (and large) images from messing up the modal alignment

TMS-1021: Fix image alignment in image-carousel modal

---

CHANGELOG.MD
assets/assets_test.html
assets/scripts/theme-mustavalkoinen.js
assets/styles/theme-mustavalkoinen.scss
assets/styles/themes/theme-mustavalkoinen-overrides.scss
lib/ACF/Fields/Settings/ThemeColorTab.php
webpack.config.js

Severa-ID: 2145
Severa-kuvaus: TMS-1019 Uusi väri kampanjateeman värimaailmavaihtoehdoksi musta-valkoinen
Task: https://hiondigital.atlassian.net/browse/TMS-1019
Added new black & white color-theme

TMS-1019: Add black & white color theme

---

CHANGELOG.MD
lib/Eventz.php
lib/Formatters/EventzFormatter.php

Severa-kuvaus: TMS-1013 Tapahtumaintegraatio: viikkokalenteri-tapahtumat
Task: https://hiondigital.atlassian.net/browse/TMS-1013
Skip dynamic events in recurring event checking

TMS-1013: Skip dynamic events in recurring event checking

---

CHANGELOG.MD
assets/styles/themes/theme-mustavalkoinen-overrides.scss

Severa-kuvaus: TMS-1038 Musta-valkoisen teeman kielivalikon hover-värin muutos
Task: https://hiondigital.atlassian.net/browse/TMS-1038
Fix theme-mustavalkoinen lang-menu styles

TMS-1038: Fix theme-mustavalkoinen lang-menu styles

---

CHANGELOG.MD
lib/Eventz.php
models/page-event.php

Severa-kuvaus: TMS-1043 Tapahtuman hidas avautuminen
Task: https://hiondigital.atlassian.net/browse/TMS-1043
- Fix date checking for event
- Minimize the amount of event data loops by creating separate 'normalize' functions for each needed field

TMS-1043: Eventz optimization

---

CHANGELOG.MD
assets/scripts/accordion.js

Severa-kuvaus: TMS-1050 Tredun Koulutukset-sivun hakuvalintahaitari ei aukea
Task: https://hiondigital.atlassian.net/browse/TMS-1050
Add if-statements and checks to prevent breaking other accordion-elements.
The new accordion script broke the functionality of an accordion-element in Tredu's program-search page template.

TMS-1050: Accordion script fixes

---

CHANGELOG.MD
assets/styles/ui-components/header/_primary-nav.scss

Severa-kuvaus: TMS-1062 Mahdollinen saavutettavuusongelma valikkojen tyylissä
Task: https://hiondigital.atlassian.net/browse/TMS-1062
Increase menu-dropdown button size

TMS-1062: Increase menu-dropdown button size

---

CHANGELOG.MD
models/search.php

Severa-kuvaus: TMS-1088 Tredun koulutushaussa ei toimi "Näytä vain haussa olevat" hakusanalla
Task: https://hiondigital.atlassian.net/browse/TMS-1088

TMS-1088: Add fields to redipress schema

---

CHANGELOG.MD
partials/blocks/block-accordion.dust

Severa-kuvaus: TMS-1091 Haitari-lohkon pieni tyylimuutos
Task: https://hiondigital.atlassian.net/browse/TMS-1091
Remove align-wide class from accordion block

TMS-1091: Remove align-wide class from accordion block

---

CHANGELOG.MD
lib/ACF/PageEventsCalendarGroup.php
models/page-events-calendar.php

Severa-kuvaus: TMS-1095 Tapahtumalistauksen listaustyyli
Task: https://hiondigital.atlassian.net/browse/TMS-1095
Add field to disable pagination for events-calendar template

TMS-1095: Add field to disable pagination for events-calendar template

---

CHANGELOG.MD
assets/styles/themes/_theme-haive-overrides.scss
assets/styles/themes/_theme-neutraali-overrides.scss
assets/styles/themes/theme-mustavalkoinen-overrides.scss
assets/styles/ui-components/_duetdatepicker.scss
assets/styles/ui-components/_forms.scss

Severa-kuvaus: TMS-1131 Tapahtumahaku-sivupohjan hakusana-kentästä puuttuu reunat
Task: https://hiondigital.atlassian.net/browse/TMS-1131
Fix event search form styles, modify duet-datepicker style overrides

TMS-1131: Events search form style changes

---

CHANGELOG.MD
assets/scripts/hero.js
lib/ACF/Fields/HeroMuseumFields.php
partials/layouts/layout-hero-museum.dust
partials/layouts/layout-hero.dust

Severa-kuvaus: TMS-1172 Kehitystä heron videoon, tietyt teemat
Task: https://hiondigital.atlassian.net/browse/TMS-1172
Add video-possibility to hero-layout

TMS-1172: Add video possibility to hero-museum layout

---

CHANGELOG.MD
lib/ACF/Fields/SomeLinkListFields.php

Severa-kuvaus: TMS-1176 Somelinkkilistaan uusi vaihtoehto, pohjateema eli kaikkiin
Task: https://hiondigital.atlassian.net/browse/TMS-1176
Add homepage-selection to some-linklist component

TMS-1176: Add homepage-selection for some-linklist fields

---

CHANGELOG.MD
assets/styles/ui-components/_duetdatepicker.scss

Severa-kuvaus: TMS-1166 Tampere Filharmonian Hae tapahtumista -sivun reunuksen värin vaihto Mozilla Firefoxissa
Task: https://hiondigital.atlassian.net/browse/TMS-1166
Change duet-datepicker input focus styles to match other theme styles

TMS-1166: Fix duet-datepicker border on focus

---

CHANGELOG.MD
models/page-events-search.php

Projekti: Tampereen kaupunki, konsernihallinto / Tietohallintoyksikkö: Tampere multisite support
Tiketin kuvaus: TMS-1199 Tampereen päivän sivuston tapahtumahaussa ajoittaisia ongelmia
Task: https://hiondigital.atlassian.net/browse/TMS-1199
Remove additional string from events-search no-results text to avoid confusion, since the deleted text had no conditional logic to it.

TMS-1199: Change events-search no-results text
